### ISSUE TITLE
Converting syntax from .services.yml into a plugin manager class...

### ISSUE THREAD

**Issue by drupol** [fabianx-ai/service_container#100]
Hi,

I'm looking for a way to convert my file geocoder.services.yml:

``` yaml
services:
  geocoder.http_adapter:
    class: \Ivory\HttpAdapter\CurlHttpAdapter

parameters:
  annotated_plugins_auto_discovery.geocoder:
    - { plugin_manager_name: 'plugin.manager.geocoder', directory: 'Plugin/Geocoder', class: 'Drupal\geocoder\Component\Annotation\GeocoderPlugin' }
```

into this:

``` yaml
services:
  geocoder.http_adapter:
    class: \Ivory\HttpAdapter\CurlHttpAdapter
  plugin.manager.geocoder:
    class: \Drupal\geocoder\GeocoderPluginManager
```

The class GeocoderPluginManager is:

``` php
<?php

namespace Drupal\geocoder;

use Drupal\Component\Plugin\Factory\DefaultFactory;
use Drupal\Component\Plugin\PluginManagerBase;
use Drupal\service_container\Plugin\DefaultPluginManager;
use Drupal\service_container_annotation_discovery\Plugin\Discovery\AnnotatedClassDiscovery;

class GeocoderPluginManager extends DefaultPluginManager {
  /**
   * @inheritdoc
   */
  public function __construct() {
    $plugin_manager_definition = array(
      'directory' => 'Plugin/Geocoder',
    );

    $this->discovery = new AnnotatedClassDiscovery($plugin_manager_definition, 'Drupal\geocoder\Component\Annotation\GeocoderPlugin');
    parent::__construct($this->discovery);
    $this->factory = new DefaultFactory($this->discovery, 'Drupal\geocoder\GeocoderPluginInterface');
  }

}
```

When I do this, I'm unable to create an object:

``` php
$object = \Drupal::service('plugin.manager.geocoder')->createInstance('googlemaps'));
```

It says:

```
Error message
TypeError: Argument 4 passed to Drupal\geocoder\Plugin\Geocoder\Provider::__construct() must be an instance of Ivory\HttpAdapter\HttpAdapterInterface, none given, called in /home/pol/dev/sites/d7x/sites/all/modules/service_container/lib/Drupal/Component/Plugin/Factory/DefaultFactory.php on line 58 in Drupal\geocoder\Plugin\Geocoder\Provider->__construct() (line 41 of /home/pol/dev/git/geocoder/src/Plugin/Geocoder/Provider.php).
```

Here's the screenshot 
![screenshot-d7x 2016-01-17 09-37-05](https://cloud.githubusercontent.com/assets/252042/12376624/9dcb7916-bcfe-11e5-8e17-26787d5f9cf8.png)

Can you help me figuring out what I'm doing wrong ?

Thanks.
